
language: generic

env:
  global:
    - CMAKE_GENERATOR="Unix Makefiles" CMAKE_OPTIONS=" "

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: BUILD_PLATFORM="Linux-x64"
    - os: osx
      osx_image: xcode7.3
      env: BUILD_PLATFORM="Darwin-x64"

before_install:
  # GCC 4.9
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - buildscripts/1-install-deps-travis.sh
  - export PATH="/data/bin:$PATH"
  # GCC 4.9
  - sudo apt-get install -qq g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

script:
  - CMAKE_BUILD_TYPE=Debug buildscripts/2-build-travis.sh
  - CMAKE_BUILD_TYPE=Release buildscripts/2-build-travis.sh

after_success:
  - CMAKE_BUILD_TYPE=Debug buildscripts/3-release-travis.sh
  - CMAKE_BUILD_TYPE=Release buildscripts/3-release-travis.sh
